### ISSUE TITLE
dodatkowy warunek

### ISSUE THREAD

**Issue by michal-bootcamp** [ewelaD/js_if#1]
- [x] poprosze Cie abys rozwinela ten skrypt na bardziej idiotoodporny. Obecnie jesli wpisze litery dostaje wynik NaN (co jest ok), ale komunikat 'liczba dodatnia'. Stworz dodatkowy warunek tak, abym w tym przypadku dostawal info 'nieprawidlowe dane'
- [x] dodaj tez sredniki na koncach linii po alertach

**Comment by ewelaD** [comment]
- nie poradziłam sobie ze sprawdzeniem typu danych: znalazłam podpowiedź, że typeof robi to 
- ale: przyjęłam, że musi sprawdzić najpierw warunek czy wynik jest liczbą - jeżeli użytkownik wrzuci coś innego to tak jak wcześniej wyskakuje info NaN (tylko w js to też jest number)
- a powinien w tym pierwszym warunku sprawdzić i przerwać działanie 
- i pytanie o operator logiczny, który sprawdza tylko typ, bez wartości, chyba w js nie ma takiego

**Comment by michal-bootcamp** [comment]
Gratulacje za wnikliwe potraktowanie tematu. Fajnie, ze sie bardziej wgryzlas, ta wiedza na pewno zaprocentuje. Do sprawdzania typow sluzy niby `typeof`, ale jest to operator problematyczny w uzyciu jak sama zauwazylas - dluzszy temat.
Poza tym `prompt` i tak zawsze zwraca stringa: https://developer.mozilla.org/pl/docs/Web/API/Window/prompt - witamy w swiecie js :)

Tutaj chodzilo mi o cos prostszego, przerobienie tych 3 ifow, ktore mialas wczesniej na 4, ktore sprawdzalyby:
- czy wynik jest wiekszy od zera
- czy wynik jest mniejszy od zera
- czy wynik JEST zerem
- reszta to nieprawidlowe dane
